Task/platform 104 common application
openlattice/access-request pull request #55
Opened 2021-03-02 06:54 UTC by solomontang

2021-03-02 18:54 UTC, bergieboy commented on src/containers/access/src/sagas/submitAccessRequest.js
> +    debugger;
should this be here?

2021-03-02 18:54 UTC, bergieboy commented on src/forms/common/CommonApplicationForm.js
> +  padding: 0 30px 30px 30px;
sort

2021-03-02 18:54 UTC, bergieboy commented on src/forms/common/CommonApplicationForm.js
> +                  uiSchema={uiSchemas[page]} />
sort

2021-03-02 19:05 UTC, giuliacampana approved these changes

2021-03-02 19:28 UTC, UnsungHero97 requested changes

2021-03-02 19:28 UTC, UnsungHero97 commented on package.json
> +    "react-to-print": "^2.12.3"
You need to add this to `externals` in the webpack config.

```
externals: [
  externals({
    allowlist: ['react-to-print'],
  }),
]
```

2021-03-02 23:56 UTC, UnsungHero97 commented on src/containers/access/src/EditAccessRequestContainer.js
> +import { useReactToPrint } from 'react-to-print';
No change required, just a thought. Maybe the parent app should be responsible for this dependency, and all the module does is pass along the ref in a `onPrint` callback or something.

2021-03-02 23:56 UTC, UnsungHero97 commented on src/containers/access/src/reducers/submitAccessRequestReducer.js
> +      .set('accessRequest', action.value)
You created the constant, might as well use it.

2021-03-02 23:56 UTC, UnsungHero97 commented on src/containers/access/src/sagas/submitAccessRequest.js
> +      [TYPE]: [type || 'Common Application'],
No change required. `|| 'Common Application'` doesn't make sense as a default in the future.

2021-03-02 23:56 UTC, UnsungHero97 commented on src/forms/common/schemas/page1Schemas.js
> +      },
No change required, just a thought. You can pull this out and reuse it for all 3.

2021-03-02 23:56 UTC, UnsungHero97 commented on src/forms/common/schemas/page1schemas.js
> +export const page1Schema = {
This is a duplicate.

2021-03-03 00:37 UTC, UnsungHero97 approved these changes

2021-03-03 01:02 UTC, giuliacampana approved these changes

2021-03-03 01:19 UTC, merged